(package "flxy"
         "0.1.0"
         "Fast, character-based search library in Rust")

(website-url "https://github.com/jcs-elpa/flxy")
(keywords "matching" "fuzzy" "search")

(package-file "flxy.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
